### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by timsmith00** [tspooner/scaRLa#2]
This framework looks really cool, you have have a simple readme that would explain some of the options and how to interpret the output of an experiment training/eval?

**Comment by tspooner** [comment]
Hey, glad you enjoyed looking over this codebase. I appreciate it's not well documented but this project kinda got dropped in favour of [rsrl](https://github.com/tspooner/rsrl) as I prefer it out of the "new generation" of languages; Scala is great too, but Rust gave me more of the control I wanted in terms of implementation. So, while I realise it's a pain, I won't have the time to work on documentation for this project. Sorry about that.

That being said, I would be very interested to see what you could do with it if you wanted to fork this repo and develop it. Could be very interesting, especially for the Horde-type architectures explored by Sutton.
